version: '3.0'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    ports:
      - 4000:4000
      - 9229:9229
    command: pnpm run start
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
